# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3255ac28507b9f28180eb71691dceb2a789db20883f00edaac38efae1840dcc74d28b820ed2a952f5c9542ad9b80da29f71e46e2c86313d2331fe3c89abc06e0

test:
  secret_key_base: c4e25b4bee7031601c6b7c5a0fb7f41534943ec5b7297297e9856e576dce8e878be7cf3169371e5ae9a8f270457869d865e4e06765bd23da3e1ccd554700ac3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
