require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DiaristasController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Diarista. As you add validations to Diarista, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DiaristasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all diaristas as @diaristas" do
      diarista = Diarista.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:diaristas)).to eq([diarista])
    end
  end

  describe "GET show" do
    it "assigns the requested diarista as @diarista" do
      diarista = Diarista.create! valid_attributes
      get :show, {:id => diarista.to_param}, valid_session
      expect(assigns(:diarista)).to eq(diarista)
    end
  end

  describe "GET new" do
    it "assigns a new diarista as @diarista" do
      get :new, {}, valid_session
      expect(assigns(:diarista)).to be_a_new(Diarista)
    end
  end

  describe "GET edit" do
    it "assigns the requested diarista as @diarista" do
      diarista = Diarista.create! valid_attributes
      get :edit, {:id => diarista.to_param}, valid_session
      expect(assigns(:diarista)).to eq(diarista)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Diarista" do
        expect {
          post :create, {:diarista => valid_attributes}, valid_session
        }.to change(Diarista, :count).by(1)
      end

      it "assigns a newly created diarista as @diarista" do
        post :create, {:diarista => valid_attributes}, valid_session
        expect(assigns(:diarista)).to be_a(Diarista)
        expect(assigns(:diarista)).to be_persisted
      end

      it "redirects to the created diarista" do
        post :create, {:diarista => valid_attributes}, valid_session
        expect(response).to redirect_to(Diarista.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved diarista as @diarista" do
        post :create, {:diarista => invalid_attributes}, valid_session
        expect(assigns(:diarista)).to be_a_new(Diarista)
      end

      it "re-renders the 'new' template" do
        post :create, {:diarista => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested diarista" do
        diarista = Diarista.create! valid_attributes
        put :update, {:id => diarista.to_param, :diarista => new_attributes}, valid_session
        diarista.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested diarista as @diarista" do
        diarista = Diarista.create! valid_attributes
        put :update, {:id => diarista.to_param, :diarista => valid_attributes}, valid_session
        expect(assigns(:diarista)).to eq(diarista)
      end

      it "redirects to the diarista" do
        diarista = Diarista.create! valid_attributes
        put :update, {:id => diarista.to_param, :diarista => valid_attributes}, valid_session
        expect(response).to redirect_to(diarista)
      end
    end

    describe "with invalid params" do
      it "assigns the diarista as @diarista" do
        diarista = Diarista.create! valid_attributes
        put :update, {:id => diarista.to_param, :diarista => invalid_attributes}, valid_session
        expect(assigns(:diarista)).to eq(diarista)
      end

      it "re-renders the 'edit' template" do
        diarista = Diarista.create! valid_attributes
        put :update, {:id => diarista.to_param, :diarista => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested diarista" do
      diarista = Diarista.create! valid_attributes
      expect {
        delete :destroy, {:id => diarista.to_param}, valid_session
      }.to change(Diarista, :count).by(-1)
    end

    it "redirects to the diaristas list" do
      diarista = Diarista.create! valid_attributes
      delete :destroy, {:id => diarista.to_param}, valid_session
      expect(response).to redirect_to(diaristas_url)
    end
  end

end
